### ISSUE TITLE
CC support?

### ISSUE THREAD

**Issue by ldong** [joshuamauldin/ios-grid-system#1]
Hi Josh,

I followed the link from [Smashing Magazine](http://www.smashingmagazine.com/2013/05/02/ios-grid-system-free-extension-adobe-fireworks/), it seems to be a really useful plugin.

Could you update this extension to support CC version instead of CS6(zxp instead of mxp)?

Thanks, 
Lin

**Comment by itsjoshuagraves** [comment]
Hi Lin,

I'd like to but would need some help in doing that. If you want to do a pull request, I'm happy to let you take a crack at it.
